/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.teleknesis.android.surveillance;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_launcher=0x7f020000;
    }
    public static final class id {
        public static final int btnCapture=0x7f050001;
        public static final int btnProceed=0x7f05000b;
        public static final int btnRecord=0x7f05000a;
        public static final int buttonPlay=0x7f050002;
        public static final int chkSaveVideo=0x7f050009;
        public static final int surface_camera=0x7f050000;
        public static final int textView2=0x7f050005;
        public static final int textView3=0x7f050007;
        public static final int txtAllFiles=0x7f050003;
        public static final int txtReceiver=0x7f050008;
        public static final int txtSender=0x7f050006;
        public static final int videoView1=0x7f050004;
    }
    public static final class layout {
        public static final int camera=0x7f030000;
        public static final int download=0x7f030001;
        public static final int main=0x7f030002;
        public static final int main2=0x7f030003;
    }
    public static final class string {
        public static final int app_name=0x7f040003;
        public static final int hello=0x7f040002;
        public static final int receiverID=0x7f040000;
        public static final int senderID=0x7f040001;
    }
}
